// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAazdRQmockjbmBPHm5gxLzHOiHzWvrDWg',
    appId: '1:444313779512:web:c5400d41107701012755cd',
    messagingSenderId: '444313779512',
    projectId: 'qrapp-5328c',
    authDomain: 'qrapp-5328c.firebaseapp.com',
    storageBucket: 'qrapp-5328c.appspot.com',
    measurementId: 'G-FPML84L0XN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbJ-KqhLNpXBgr3IN5I6_KAdFcijC2F48',
    appId: '1:444313779512:android:39e5ede3ad9f2d102755cd',
    messagingSenderId: '444313779512',
    projectId: 'qrapp-5328c',
    storageBucket: 'qrapp-5328c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD36PLGBF4EjhhsWtgbhfbv32L4WHpaJ5M',
    appId: '1:444313779512:ios:38f6b0e3a9e996e42755cd',
    messagingSenderId: '444313779512',
    projectId: 'qrapp-5328c',
    storageBucket: 'qrapp-5328c.appspot.com',
    iosBundleId: 'com.example.qrApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD36PLGBF4EjhhsWtgbhfbv32L4WHpaJ5M',
    appId: '1:444313779512:ios:510ad921cf3ac8c12755cd',
    messagingSenderId: '444313779512',
    projectId: 'qrapp-5328c',
    storageBucket: 'qrapp-5328c.appspot.com',
    iosBundleId: 'com.example.qrApp.RunnerTests',
  );
}
